name: env-name-here-does-not-matter
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
 - trinity
 - Cutadapt
 - jellyfish
 - multiqc
 - fastqc=0.11.8
 - sortmerna=2.1b
 - trim-galore=0.6.4
 - rcorrector=1.0.4
